Lesson 1/PartII.md
The first time I tried to run prod-debug I was following this tutorial to the letter. Took me way too long to realize you need to add the task to the node first. :upside_down_face:
=> add task to node instructions

README.md
This is a guide for people who want to develop tasks, so I think we can assume some level of technical proficiency. The explanation of the node felt oversimplified to me.
=> Change description of koii node

Lesson 5/README.md, Lesson 6/README.md, Lesson 7/Lesson 8/README.md, Lesson 7/README.md
As we're adding the landing page to the homepage that includes links to all the lessons, we're adding placeholders for the future lessons so the links won't be broken and we don't need to keep updating the page.
=> Create Lesson Placeholders

Lesson 1/hello-world/.env.local.example, Lesson 1/hello-world/config-task.yml, Lesson 2/upnp-task/.env.local.example, Lesson 2/upnp-task/config-task.yml, Lesson 3/README.md, Lesson 3/simple-crawler/.env.example, Lesson 3/simple-crawler/.env.local.example, Lesson 3/simple-crawler/config-task.yml, Lesson 3/simple-crawler/crawler/SimpleCrawlerTask.js, Lesson 3/simple-crawler/package.json, Lesson 3/simple-crawler/task/submission.js, Lesson 3/simple-crawler/yarn.lock, Lesson 4/caesar-task/.env.local.example, Lesson 4/caesar-task/config-task.yml
- remove all references to Spheron
- update lesson 3's simple crawler task to use the Storage SDK instead of Spheron
=> Change Spheron to storage SDK

Lesson 7/README.md
=> Lesson 7 complete

Lesson 3/PartIII.md
There was a comment in the code regarding the headless property, but I added a note to the text to make it more obvious.
=> Add note about headless false

Lesson 0/README.md, README.md
Add a quick start guide that provides the minimal steps to get a task running.
=> Lesson 0 complete

Lesson 1/PartIII.md
The .env variable mentioned in the lesson 1 section on prod-debug should be TEST_KEYWORD, not KEYWORD. This is causing the logging to the console to fail.
=> env variable in lesson 1 is incorrect

Get Started - Quick Intro/testing.md, Lesson 2/PartIV.md
=> update config url

Lesson 1/EZ-testing-task/package.json, Lesson 2/file-sharing/after/package.json, Lesson 2/file-sharing/before/package.json, Lesson 2/upnp-basics/after/package.json, Lesson 2/upnp-basics/before/package.json, Lesson 3/simple-crawler/after/package.json, Lesson 3/simple-crawler/before/package.json, Lesson 4/caesar-task/after/package.json
=> switch from jest to unittest

Lesson 2/PartIII.md, Lesson 2/file-sharing/after/task/fileUtils/storeFile.js
Lesson 2 Part 3 was missing the import
=> add missing namespacewrapper import

Get Started - Quick Intro/README.md, Get Started - Quick Intro/deployment.md, Get Started - Quick Intro/testing.md, Lesson 1/EZ-testing-task/README.md, Lesson 1/EZ-testing-task/prod-debug.js, Lesson 1/PartII.md, Lesson 2/PartII.md, Lesson 2/file-sharing/after/README.md, Lesson 2/file-sharing/after/prod-debug.js, Lesson 2/file-sharing/before/README.md, Lesson 2/file-sharing/before/prod-debug.js, Lesson 2/upnp-basics/after/README.md, Lesson 2/upnp-basics/after/prod-debug.js, Lesson 2/upnp-basics/before/README.md, Lesson 2/upnp-basics/before/prod-debug.js, Lesson 3/prod-debug.js, Lesson 3/simple-crawler/after/README.md, Lesson 3/simple-crawler/before/README.md, Lesson 3/simple-crawler/before/prod-debug.js, Lesson 4/caesar-task/after/README.md, Lesson 4/caesar-task/after/prod-debug.js, Lesson 4/caesar-task/before/README.md, Lesson 4/caesar-task/before/prod-debug.js, Lesson 7/README.md
=> Yarn to npm

Lesson 1/PartIII.md
=> Lesson 1 - Part 3: Fix Part IV Link

Lesson 2/file-sharing/after/task/fileUtils/storeFile.js, Lesson 3/simple-crawler/after/package.json
* Closes #90 -  add `'puppeteer-chromium-resolver'` to package.json
=> Bug fix for #90 (Lesson 3) and #92 (Lesson 2)

Lesson 3/simple-crawler/after/crawler/SimpleCrawlerTask.js
=> Bugfix for #93: Create Instance Before module.export

Get Started - Quick Intro/README.md, Get Started - Quick Intro/deployment.md, Get Started - Quick Intro/testing.md, Lesson 1/EZ-testing-task/README.md, Lesson 1/PartII.md, Lesson 1/PartIV.md, Lesson 2/PartII.md, Lesson 2/file-sharing/after/README.md, Lesson 2/file-sharing/before/README.md, Lesson 2/upnp-basics/after/README.md, Lesson 2/upnp-basics/before/README.md, Lesson 3/simple-crawler/after/README.md, Lesson 3/simple-crawler/before/README.md, Lesson 4/caesar-task/after/README.md, Lesson 4/caesar-task/before/README.md, Lesson 7/README.md
According to hackathon feedback, some people ran into version conflicts when using NPM, so we're recommending yarn instead.
Closes #111
=> NPM to yarn

Lesson 3/simple-crawler/after/debugger.js, Lesson 3/simple-crawler/after/prod-debug.js, Lesson 3/simple-crawler/after/test.webpack.config.js
=> add missing debug files

Lesson 1/PartIV.md
Adjusted the language to make it clearer and added emphasis to the part about running a task.
=> make it clear you must run a task for staking wallet to work

Lesson 3/PartIII.md
Rewrote the explanation of headless mode and made it a separate subsection.
=> make the explanation of headless: false more prominent

Lesson 1/EZ-testing-task/config-task.yml, Lesson 2/file-sharing/after/config-task.yml, Lesson 2/file-sharing/after/task/fileUtils/storeFile.js, Lesson 2/file-sharing/before/config-task.yml, Lesson 2/upnp-basics/after/config-task.yml, Lesson 2/upnp-basics/before/config-task.yml, Lesson 3/simple-crawler/after/config-task.yml, Lesson 3/simple-crawler/before/config-task.yml, Lesson 4/caesar-task/after/config-task.yml, Lesson 4/caesar-task/before/config-task.yml
to work with most create task cli update
=> Update config task yaml

Lesson 2/upnp-basics/src/routes.js, Lesson 2/upnp-basics/src/task/1-task.js, Lesson 2/upnp-basics/src/task/upnpUtils.js
=> Fix upnp task
